package com.womenshop.dao;

import java.sql.*;

public class DatabaseInitializer {

    public static void initialize() {
        try (Connection conn = DBConnection.getConnection();
             Statement stmt = conn.createStatement()) {

            if (!tableExists(conn, "PRODUCTS")) {
                stmt.execute(
                    "CREATE TABLE products (" +
                    "    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY," +
                    "    name VARCHAR2(100) NOT NULL," +
                    "    purchase_price NUMBER(10,2) NOT NULL," +
                    "    sell_price NUMBER(10,2) NOT NULL," +
                    "    discount_price NUMBER(10,2) DEFAULT 0," +
                    "    nb_items NUMBER DEFAULT 0," +
                    "    total_sold NUMBER DEFAULT 0," +
                    "    total_bought NUMBER DEFAULT 0," +
                    "    category VARCHAR2(20) CHECK (category IN ('CLOTHES','SHOES','ACCESSORY'))" +
                    ")"
                );
                System.out.println("[DB] Created table: products");
            }

            if (!tableExists(conn, "CLOTHES")) {
                stmt.execute(
                    "CREATE TABLE clothes (" +
                    "    product_id NUMBER PRIMARY KEY," +
                    "    size_val NUMBER NOT NULL," +
                    "    CONSTRAINT fk_clothes FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE" +
                    ")"
                );
                System.out.println("[DB] Created table: clothes");
            }

            if (!tableExists(conn, "SHOES")) {
                stmt.execute(
                    "CREATE TABLE shoes (" +
                    "    product_id NUMBER PRIMARY KEY," +
                    "    shoe_size NUMBER NOT NULL," +
                    "    CONSTRAINT fk_shoes FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE" +
                    ")"
                );
                System.out.println("[DB] Created table: shoes");
            }

            if (!tableExists(conn, "STORE_FINANCES")) {
                stmt.execute(
                    "CREATE TABLE store_finances (" +
                    "    id NUMBER DEFAULT 1 PRIMARY KEY," +
                    "    initial_capital NUMBER(10,2) DEFAULT 30000," +
                    "    total_income NUMBER(10,2) DEFAULT 0," +
                    "    total_cost NUMBER(10,2) DEFAULT 0" +
                    ")"
                );
                stmt.execute(
                    "INSERT INTO store_finances (id, initial_capital, total_income, total_cost) VALUES (1, 30000, 0, 0)"
                );
                System.out.println("[DB] Created table: store_finances");
            }

            System.out.println("[DB] Database initialization complete.");

        } catch (SQLException e) {
            System.err.println("[DB] Initialization error: " + e.getMessage());
            e.printStackTrace();
        }
    }

    private static boolean tableExists(Connection conn, String tableName) throws SQLException {
        DatabaseMetaData meta = conn.getMetaData();
        try (ResultSet rs = meta.getTables(null, conn.getSchema(), tableName, new String[]{"TABLE"})) {
            return rs.next();
        }
    }
}
