-- Table principale
CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    purchase_price NUMBER(10,2) NOT NULL,
    sell_price NUMBER(10,2) NOT NULL,
    discount_price NUMBER(10,2) DEFAULT 0,
    nb_items NUMBER DEFAULT 0,
    category VARCHAR2(20) CHECK (category IN ('CLOTHES', 'SHOES', 'ACCESSORY'))
);

-- Tables filles
CREATE TABLE clothes (
    product_id NUMBER PRIMARY KEY,
    size_val NUMBER NOT NULL,
    CONSTRAINT fk_clothes FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

CREATE TABLE shoes (
    product_id NUMBER PRIMARY KEY,
    shoe_size NUMBER NOT NULL,
    CONSTRAINT fk_shoes FOREIGN KEY (product_id) REFERENCES products(id) ON DELETE CASCADE
);

-- Finances
CREATE TABLE store_finances (
    id NUMBER DEFAULT 1 PRIMARY KEY,
    initial_capital NUMBER(10,2) DEFAULT 30000,
    total_income NUMBER(10,2) DEFAULT 0,
    total_cost NUMBER(10,2) DEFAULT 0
);

INSERT INTO store_finances (id, initial_capital, total_income, total_cost) VALUES (1, 30000, 0, 0);
COMMIT;